#!/bin/bash
function install_nvidia_driver(){
  if pgrep -Qi "hyprland"; then
    echo "hyprland is running. Please exit hyprland before installing nvidia driver." >&2
    return 1
  fi
  if ! sudo pacman -S --noconfirm linux-zen-headers; then
    echo "Fatal error! Failed to install linux-zen-headers." >&2
    return 1
  fi
  if ! yay -S nvidia-dkms nvidia-utils lib32-nvidia-utils; then
    echo "Fatal error! Failed to install nvidia-dkms." >&2
    return 1
  fi

  if ! yay -S --noconfirm nvidia-settings; then
    echo "Fatal error! Failed to install nvidia-settings." >&2
    return 1
  fi

}

function update_grub(){
  # Check if modset is already set
  if grep -q "nvidia_drm.modeset=1" /etc/default/grub; then
    echo "nvidia_drm.modeset=1 is already set in /etc/default/grub" >&2
    return 0
  fi

  sudo sed -i "/^GRUB_CMDLINE_LINUX_DEFAULT=/s/\"\$/ nvidia_drm.modeset=1\"/" /etc/default/grub
  if sudo grub-mkconfig -o /boot/grub/grub.cfg; then
    echo "GRUB configuration generated successfully." >&2
  else
    echo "Fatal error! GRUB configuration generation failed." >&2
     return 1
  fi
}

function update_mkinitcpio(){
  local nvidia_modules
  local module
  local modules_updated
  modules_updated=0
  nvidia_modules="nvidia nvidia_modeset nvidia_uvm nvidia_drm"

  for module in $nvidia_modules; do
    if grep -q "$module" /etc/mkinitcpio.conf; then
      echo "$module is already set in /etc/mkinitcpio.conf" >&2
      continue
    fi
      sudo sed -i "/^MODULES=/s/)$/ $module)/" /etc/mkinitcpio.conf
      modules_updated=1
  done

  sudo sed -i "/^HOOKS=/s/kms//" /etc/mkinitcpio.conf

  if (( ! modules_updated )); then
    return 0
  fi

  if sudo mkinitcpio -P; then
    echo "Linux initramfs generated successfully." >&2
  else
    echo "Fatal error! Linux initramfs generation failed." >&2
    return 1
  fi
}
function update_hyprland_env(){

  if grep -i "LIBVA_DRIVER_NAME" "$HOME"/.config/hypr/.env; then
    echo "hyprland env is already set" >&2
    return 0
  fi

  echo "env = LIBVA_DRIVER_NAME,nvidia
env = XDG_SESSION_TYPE,wayland
env = GBM_BACKEND,nvidia-drm
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = WLR_NO_HARDWARE_CURSORS,1" >> "$HOME"/.config/hypr/.env

  echo "env = LIBVA_DRIVER_NAME,nvidia
env = XDG_SESSION_TYPE,wayland
env = GBM_BACKEND,nvidia-drm
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = WLR_NO_HARDWARE_CURSORS,1" >> /etc/skel/.config/hypr/.env

  echo "hyprland env updated successfully." >&2
}

#if ! install_nvidia_driver; then
#  echo "Fatal error! Failed to install nvidia driver." >&2
#  exit 1
#fi


#if ! update_grub; then
#  echo "Fatal error! Failed to update grub." >&2
#  exit 1
#fi

#if ! update_mkinitcpio; then
#  echo "Fatal error! Failed to update mkinitcpio." >&2
#  exit 1
#fi

if ! update_hyprland_env; then
  echo "Fatal error! Failed to update hyprland env." >&2
   exit 1
fi

#echo "Nvidia driver installed successfully. Rebooting sytem..." >&2
#sleep 5
#reboot

