#!/bin/bash
# shellcheck source=utils
source "$SCRIPT_DIR/includes/utils"

function copy_bin() {
    if ! sudo cp -rv "$SCRIPT_DIR"/files/scripts/* $1; then
        echo "Failed to copy scripts to $1" >&2
        return 1
    fi
}
export -f copy_scripts


# copy /etc/NetworkManager/wifi_backend.conf to /etc/NetworkManager/conf.d/wifi_backend.conf
# copy /etc/NetworkManager/dhcp-client.conf to /etc/NetworkManager/conf.d/wifi_backend.conf
function copy_network_manager_configs(){
  if ! sudo cp -rfv "$SCRIPT_DIR"/files/system/etc/NetworkManager/* /etc/NetworkManager/conf.d/; then
    echo "Failed to copy NetworkManager configs to /etc/NetworkManager/conf.d/" >&2
    return 1
  fi
}

# Copy cappuccino rofi theme
function copy_rofi_usr_theme(){
  # .config part will be copied along with everything else later
  if ! sudo cp -rfv "$SCRIPT_DIR"/files/system/usr/share/rofi/themes/* /usr/share/rofi/themes/; then
    echo "Failed to copy rofi theme to /usr/share/rofi/themes/" >&2
    return 1
  fi
}

function copy_modprobe(){
  if ! sudo cp -rfv "$SCRIPT_DIR"/files/system/etc/modprobe/* /etc/modprobe.d/; then
    echo "Failed to copy modprobe configs to /etc/modprobe.d/" >&2
    return 1
  fi
}

function copy_dots(){
  if ! sudo cp -rfv "$SCRIPT_DIR"/files/user/.config/* "$HOME"/.config/; then
    echo "Failed to copy dotfiles to $HOME/.config/" >&2
    return 1
  fi
}